---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    description: "Allow job creation"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ include "openfero.fullname" . }}-create-jobs
  labels:
    {{- include "openfero.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - resources:
    - jobs
    apiGroups:
    - batch
    verbs:
    - create
    - get
    - list
    - delete