# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - github_actions
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🏧 CI
      labels:
        - github_actions
        - automation
