# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🏧 CI
      labels:
        - github_actions
        - automation
    - title: Misc
      labels:
        - "*"
