apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openfero-manager-role
rules:
  - apiGroups:
      - openfero.io
    resources:
      - remediationjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
