# Source: openfero/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfero
  namespace: openfero
  labels:
    helm.sh/chart: openfero-0.1.0
    app.kubernetes.io/name: openfero
    app.kubernetes.io/instance: openfero
    app.kubernetes.io/version: "0.7.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openfero
      app.kubernetes.io/instance: openfero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        helm.sh/chart: openfero-0.1.0
        app.kubernetes.io/name: openfero
        app.kubernetes.io/instance: openfero
        app.kubernetes.io/version: "0.7.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: openfero
      securityContext:
        {}
      containers:
        - name: openfero
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "ghcr.io/payback159/openfero:0.7.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {}
