# Source: openfero/templates/rolebinding-create-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    description: "Allow job creation"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: openfero-create-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfero-create-jobs
subjects:
  - kind: ServiceAccount
    name: openfero
    namespace: openfero
