linters-settings:
  staticcheck:
    checks:
      - all
      - '-G114' # disable the rule G114
  govet:
    # report about shadowed variables
    check-shadowing: true
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true