
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfero

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    description: "Allow job creation"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: openfero-create-jobs
  labels:
    name: "openfero"
  namespace: default
rules:
- resources:
  - jobs
  apiGroups:
  - batch
  verbs:
  - create
  - get
  - list
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    description: "Allow job creation"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: openfero-create-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfero-create-jobs
subjects:
- kind: ServiceAccount
  name: openfero
  namespace: default
