apiVersion: v2
name: openfero
description: OpenFero is intended as an event-triggered job scheduler framework for code agnostic recovery jobs.
type: application
version: 0.2.1
appVersion: 0.14.0-nightly.test
