---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openfero.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openfero.labels" . | nindent 4 }}
spec:
  clusterIP: None  # Headless service
  selector:
    {{- include "openfero.selectorLabels" . | nindent 4 }}
  ports:
  - port: 7946
    name: memberlist
