{{- if include "openfero.shouldSetAlertStoreType" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openfero.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
    minAvailable: 1
    selector:
      matchLabels:
      {{- include "openfero.selectorLabels" . | nindent 6 }}
{{- end }}
