---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    description: "Allow reading job-definitions configMap"
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: {{ include "openfero.fullname" . }}-read-jobs-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openfero.labels" . | nindent 4 }}
rules:
  - resources:
    - configmaps
    apiGroups: [""]
    verbs:
    - get
    - list
    - watch
