apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: remediationjob.openfero.io
spec:
  group: openfero.io
  names:
    kind: RemediationJob
    listKind: RemediationJobList
    plural: remediationjobs
    singular: remediationjob
    shortNames:
      - rj
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - template
              properties:
                template:
                  type: object
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                      properties:
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              image:
                                type: string
                              command:
                                type: array
                                items:
                                  type: string
                              args:
                                type: array
                                items:
                                  type: string
                              env:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
                        restartPolicy:
                          type: string
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
