# .github/workflows/release.yml
name: Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New tag"
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write  # Add permission to create pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: echo Input
        run: |
          # Mark the release as pre-release
          echo $RELEASE_TAG
        env:
          RELEASE_TAG: ${{ github.event.inputs.tag }}



